# This workflow will install Python dependencies,
# build the HTML documentation using Sphinx and upload it as artifact
name: Sphinx Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-sphinx:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Make HTML Documentation
      run: |
        pushd doc
        make html
        popd
    - name: Tar HTML Documentation
      run: |
        pushd doc/_build
        tar -czf html.tar.gz html
        popd
    - name: Upload HTML Documentation
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v2
      with:
        name: HTML Documentation
        path: doc/_build/html.tar.gz
